language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master

sudo: required

cache: false

env:
  global:
    - LIBHANDLEBARS_VERSION=v0.6.4
    - PHP_PSR_VERSION=v0.5.1
    - PREFIX="$HOME/build"
    - PATH="$PREFIX/bin:$PATH"
    - CFLAGS="-L$PREFIX/lib"
    - CPPFLAGS="-I$PREFIX/include"
    - PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
    - secure: "FsLO9DoQipJjNT4/4uJH2w6kwiGscXzaKmC+nktR1/Y0fPF9a69qmqo6owxXcb0DXwq0kqQ9eCepYIz6iy3L/XK4bNfwXkq1x8LIG7/oPrwuzIjNBXdSvxtSDa8G6NNFAvWJHiw/HKMP4cMfIqAJqemmKnpvgGowK4mcZl252UU="

branches:
  only:
    - master
    - travis
    - ci

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'
  include:
    - language: nix
      php:
      before_install: nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
      install:
      before_script:
      script: nix-build --argstr phpHandlebarsVersion $TRAVIS_BRANCH --arg php "(import <nixpkgs> {}).$NIX_PHP_ATTR" | tee result.txt
      after_success: cat result.txt | cachix push jbboehr-ci
      after_failure:
      env:
        - NIX_PHP_ATTR=php71
    - language: nix
      php:
      before_install: nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
      install:
      before_script:
      script: nix-build --argstr phpHandlebarsVersion $TRAVIS_BRANCH --arg php "(import <nixpkgs> {}).$NIX_PHP_ATTR" | tee result.txt
      after_success: cat result.txt | cachix push jbboehr-ci
      after_failure:
      env:
        - NIX_PHP_ATTR=php72

before_install:
  - travis_retry sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry sudo apt-add-repository -y ppa:jbboehr/build-deps
  - travis_retry sudo apt-add-repository -y ppa:jbboehr/handlebars
  - travis_retry sudo apt-get update -y
  - travis_retry sudo apt-get install -y automake bison check flex gcc-4.9 gperf lcov libjson-c-dev liblmdb-dev libpcre3-dev libtalloc-dev libyaml-dev pkg-config re2c valgrind
  - travis_retry gem install coveralls-lcov

install:
  - ./.travis.sh
  - phpize
  - ./configure --enable-handlebars CFLAGS="--coverage -fprofile-arcs -ftest-coverage $CFLAGS" LDFLAGS="--coverage"
  - make clean all install

before_script:
  - php generate-tests.php
  - lcov --directory . --zerocounters
  - lcov --directory . --capture --compat-libtool --initial --output-file coverage.info

script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_EXECUTABLE=`which php`
  - php run-tests.php -d extension=psr.so -d extension=handlebars.so -n ./tests/

after_success:
  - lcov --no-checksum --directory . --capture --compat-libtool --output-file coverage.info
  - lcov --remove coverage.info "/usr*" --remove coverage.info "*/.phpenv/*" --remove coverage.info "/home/travis/build/include/*" --compat-libtool --output-file coverage.info
  - coveralls-lcov coverage.info

after_failure:
  - for i in `find tests -name "*.out" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
  - for i in `find tests -name "*.mem" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done


