sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  - php: 'master'
    env:
    - PHP_PSR_VERSION=v1.0.1
  include:
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: 'master'
  - language: php
    php: '7.2'
    env:
    - PHP_PSR_VERSION=v1.0.1
  - language: php
    php: '7.3'
    env:
    - PHP_PSR_VERSION=v1.0.1
  - language: php
    php: '7.4'
    env:
    - PHP_PSR_VERSION=v1.0.1
  - language: php
    php: 'master'
    env:
    - PHP_PSR_VERSION=v1.0.1

env:
  global:
  - LIBHANDLEBARS_VERSION=v0.7.3

cache: ccache

branches:
    only:
    - master
    - develop
    - travis
    - dev-0.9.x

addons:
  apt:
    packages:
    - bison
    - check
    - flex
    - gperf
    - lcov
    - libjson-c-dev
    - liblmdb-dev
    - libpcre3-dev
    - libtalloc-dev
    - libyaml-dev
    - re2c
    - valgrind

before_install:
  - source ./.ci/travis_env.sh
  - before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
