language: php

before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq autoconf automake check bison flex gawk gcc git-core lcov libjson0-dev libtalloc-dev libtool m4 make pkg-config uthash-dev
#  - travis_retry git submodule update --init --recursive
  - travis_retry git clone https://github.com/jbboehr/handlebars.c handlebars-c
  - cd handlebars-c
  - ./bootstrap
  - ./configure
  - sudo make install
  - sudo ldconfig
  - cd ..

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

branches:
  only:
    - master

script:
  - phpize
  - CPPFLAGS="-I/usr" ./configure --enable-handlebars
  - make
  - php generate-tests.php
  - echo n | make test

