sudo: false

dist: xenial

services:
- docker

matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  - php: 'master'
    env:
    - PHP_PSR_VERSION=v1.0.0
  - language: nix
    env:
      - NIX_CHANNEL=unstable
      - NIX_PHP_ATTR=php74
  - language: nix
    env:
      - NIX_CHANNEL=unstable
      - NIX_PHP_ATTR=php
  include:
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: '7.4'
    env:
    - HARDENING=true
  - language: php
    php: 'master'
  - language: php
    php: '7.2'
    env:
    - PHP_PSR_VERSION=v1.0.0
  - language: php
    php: '7.3'
    env:
    - PHP_PSR_VERSION=v1.0.0
  - language: php
    php: '7.4'
    env:
    - PHP_PSR_VERSION=v1.0.0
  - language: php
    php: 'master'
    env:
    - PHP_PSR_VERSION=v1.0.0
  - language: nix
    env:
    - NIX_CHANNEL=18.09
    - NIX_PHP_ATTR=php72
  - language: nix
    env:
    - NIX_CHANNEL=19.03
    - NIX_PHP_ATTR=php73
  - language: nix
    env:
    - NIX_CHANNEL=20.03
    - NIX_PHP_ATTR=php74
  - env:
    - DOCKER_IMAGE=fedora31
#   - language: nix
#     env:
#     - NIX_CHANNEL=unstable
#     - NIX_PHP_ATTR=php

env:
  global:
  - LIBHANDLEBARS_VERSION=354923fc39c1a2502dceb15af27f91ff7cf570b3

cache: ccache

branches:
    only:
    - master
    - develop
    - travis

addons:
  apt:
    packages:
    - bison
    - check
    - flex
    - gperf
    - lcov
    - libjson-c-dev
    - liblmdb-dev
    - libpcre3-dev
    - libtalloc-dev
    - libyaml-dev
    - re2c
    - valgrind

before_install:
  - source ./.ci/travis_env.sh
  - before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
