language: php

php:
# not supported on trusty
#  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: required

dist: trusty

env:
  global:
    - LIBHANDLEBARS_VERSION=vm
    - PHP_PSR_VERSION=v0.2.2
    - PREFIX="$HOME/build"
    - PATH="$PREFIX/bin:$PATH"
    - CFLAGS="-L$PREFIX/lib"
    - CPPFLAGS="-I$PREFIX/include"
    - PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"

branches:
  only:
    - dev-0.4
    - dev-0.5
    - master
    - travis

cache: false

before_install:
  - travis_retry sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry sudo apt-add-repository -y ppa:jbboehr/ppa
  - travis_retry sudo apt-get update -y
  - travis_retry sudo apt-get install -y automake bison check flex gcc-4.9 gperf lcov libjson-c-dev liblmdb-dev libpcre3-dev libtalloc-dev libyaml-dev pkg-config valgrind
  - travis_retry gem install coveralls-lcov

install:
  - ./.travis.sh
  - phpize
  - ./configure --enable-handlebars CFLAGS="--coverage -fprofile-arcs -ftest-coverage $CFLAGS" LDFLAGS="--coverage"
  - make clean all

before_script:
  - php generate-tests.php
  - lcov --directory . --zerocounters
  - lcov --directory . --capture --compat-libtool --initial --output-file coverage.info

script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_EXECUTABLE=`which php`
  - php run-tests.php -d extension=handlebars.so -d extension_dir=modules -n ./tests/

after_success:
  - lcov --no-checksum --directory . --capture --compat-libtool --output-file coverage.info
  - lcov --remove coverage.info "/usr*" --remove coverage.info "*/.phpenv/*" --remove coverage.info "/home/travis/build/include/*" --compat-libtool --output-file coverage.info
  - coveralls-lcov coverage.info

after_failure:
  - for i in `find tests -name "*.out" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
  - for i in `find tests -name "*.mem" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done


