sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  - language: nix
    env:
      - NIX_CHANNEL=unstable
      - NIX_PHP_ATTR=php
  include:
  - language: php
    php: '7.0'
  - language: php
    php: '7.1'
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: 'master'
  - language: nix
    env:
    - NIX_CHANNEL=18.03
    - NIX_PHP_ATTR=php70
  - language: nix
    env:
    - NIX_CHANNEL=18.09
    - NIX_PHP_ATTR=php71
  - language: nix
    env:
    - NIX_CHANNEL=18.09
    - NIX_PHP_ATTR=php72
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php

env:
    global:
    - LIBHANDLEBARS_VERSION=v0.6.4
    - PHP_PSR_VERSION=v0.5.1
    - secure: "FsLO9DoQipJjNT4/4uJH2w6kwiGscXzaKmC+nktR1/Y0fPF9a69qmqo6owxXcb0DXwq0kqQ9eCepYIz6iy3L/XK4bNfwXkq1x8LIG7/oPrwuzIjNBXdSvxtSDa8G6NNFAvWJHiw/HKMP4cMfIqAJqemmKnpvgGowK4mcZl252UU="

cache: ccache

branches:
    only:
    - master
    - develop
    - travis

addons:
  apt:
    packages:
    - bison
    - check
    - flex
    - gperf
    - lcov
    - libjson-c-dev
    - liblmdb-dev
    - libpcre3-dev
    - libtalloc-dev
    - libyaml-dev
    - re2c
    - valgrind

before_install:
  - source ./.ci/travis_env.sh
  - before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
